- package.json
- src/App.js
- src/pages/AuthPage.js
- src/pages/DetailPage.js
- src/pages/FreeBoard.js
- src/pages/MainPage.js
- src/pages/MyPage.js
- src/pages/NoticeBoard.js
- src/pages/ProjectBoard.js
- src/pages/QuestionBoard.js
- src/routes/Router.js
- 제목 : feat(#22): 기본 라우팅 설정
<br/>
작업 편의성을 위해 각 페이지에 대한 기본적인 라우팅 설정을 구현
- 메인페이지: /
- 자유게시판: /community/free
- 질문게시판: /community/questions
- 프로젝트 게시판: /community/projects
- 공지사항: /community/notices
- 마이페이지: /my-page
- 상세페이지: /detail
- 로그인, 회원가입, 아이디 찾기, 비밀번호 찾기: /auth
<br/>
이슈에 작업 상세내용 같은거 적고 작업해주시면 좋겠습니다!
그리고 이제 저희 project 페이지 보면 어떤 작업하고있는지 확인할 수 있으니까 작업 준비 중인 이슈는 ready로, 작업 중인 이슈는 in progress로, pr 생성 시 In review로 옮겨주시면 감사하겠습니다!
디스코드에 올린 pr한 브랜치 가져오는 방법으로 코드 확인해주세요~~
> feat(#22): 기본 라우팅 설정

- package-lock.json
- package.json
- 제목 : chore(#26): styled components 추가
<br/>
- styled components 추가
<br/>
제가 main에 브랜치 병합하면
서현님 제외(서현님은 이미 styled components 추가하셔서 그렇습니다)하고 작업하고 계신 브랜치에서
- git fetch origin
- git merge origin/main
하시고 진행해주시면 됩니다.
-> main의 변경된 사항을 내 브랜치에 병합
npm install
> chore(#26): styled components 추가

- src/components/Common/Interactions.js
- src/components/Feature/NoticePostCard.js
- src/pages/NoticeBoard.js
- src/services/api.js
- 제목 : feat(#10): 게시글 카드 스켈레톤 구현 - 공지사항
<br/>
- 게시글 카드의 기본 구조를 설정
- API 호출 구조 추가
<br/>
<br/>
일단 공지사항 디자인이 정해지지 않아서 보통 사용하는 기본 레이아웃으로 구현했습니다
> Feat/#10 게시글 카드 스켈레톤 구현 - 공지사항

- src/components/Common/AuthCommonComponents.js
- src/components/Feature/Login.js
- src/components/Feature/SignUp.js
- src/routes/Router.js
<br/>
- feat#12 스타일 변경 작업 내용 이어서 작업
- 공통 스타일 컴포넌트 분리
- border 생성
- margin, padding 변경
<br/>
<br/>
>
> Feat/#20: 로그인/회원가입 스켈레톤 스타일 변경

- package-lock.json
- src/routes/Router.js
- 제목 : refactor(#17): 병합문제 해결
ex) feat(#17): pull request template 작성
(확인 후 지워주세요)
<br/>
메인에 병합하다. 에러 발생해서 #17에서 수정해서 pr 만들었습니다
<br/>
> refactor(#17): 병합문제 해결

- package-lock.json
- package.json
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/components/Modal/FormInputField.jsx
- src/components/Modal/LoginModal/LoginModal.jsx
- src/services/authApi.js
- 제목 : feat(#57 ): 로그인 api 구현
<br/>
- 로그인창 모달로 변경
- 로그인 api 구현
<br/>
Closes #57
> Feat/#57 로그인 api 구현

- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/services/authApi.js
- 제목 : feat(#68 ): 로그아웃 api 구현
<br/>
- 로그아웃 api 구현
- 다크모드 버튼에 임시 로그아웃 온클릭 이벤트 생성
<br/>
Closes #68
> Feat/#68 로그아웃 api 구현

- src/Layout/Navbar/Navbar.jsx
- 제목 : feat(#93): 병합 오류 해결
<br/>
- 버튼 부분 수정 (다크모드, 로그인, 회원가입 부분)
<br/>
Closes #93
> fix(#93): 병합 오류 해결

- package-lock.json
- package.json
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/components/Card/PostCard/CommunityPostCard/CommunityPostCard.jsx
- src/components/Card/PostCard/PostProfile.jsx
- src/components/Card/PostCard/ProjectPostCard/ProjectPostCard.jsx
- src/index.js
- src/pages/DetailPage/DetailPage.jsx
- src/pages/MainPage/MainPage.jsx
- src/pages/MyPage/EditProfile/EditProfile.jsx
- src/pages/MyPage/MyProfile/MyProfile.jsx
- src/services/authApi.js
- src/store/index.js
- src/store/user/userSlice.js
- 제목 : feat(#77 ): 회원정보 수정 api 구현
<br/>
- 회원정보 수정 api 구현
- api로 데이터 받으면 전역 상태 업데이트
<br/>
Closes #77
> Feat/#77 회원정보 수정 api 구현

- src/Layout/BoardLayout/BoardLayout.jsx
- src/Layout/BoardLayout/BoardLayout.style.js
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/Layout/Sidebar/Sidebar.jsx
- src/Layout/Sidebar/Sidebar.style.js
- src/components/Card/PopularCard/PopularHashCard/PopularHashCard.jsx
- src/components/Card/PopularCard/PopularPostCard/PopularPostCard.jsx
- src/components/Card/PostCard/CommunityPostCard/CommunityPostCard.jsx
- src/components/Card/PostCard/NoticePostCard/NoticePostCard.jsx
- src/index.js
- src/pages/FreeBoard/FreeBoard.jsx
- src/pages/MainPage/MainPage.jsx
- src/pages/MainPage/MainPage.style.js
- src/pages/NoticeBoard/NoticeBoard.jsx
- src/pages/ProjectBoard/ProjectBoard.jsx
- src/pages/QuestionBoard/QuestionBoard.jsx
- src/routes/Router.js
- src/services/api.js
- 제목 : feat(#89 ): 메인페이지, 네브바, 사이드바 클릭이벤트 구현
<br/>
- 네브바 카테고리별 온클릭, 라우팅
-  메인페이지 버튼 온클릭, 라우팅
- 사이드바 카테고리별 온클릭, 라우팅
<br/>
Closes #89
> Feat/#89 메인페이지, 네브바, 사이드바 클릭이벤트 구현

- src/App.test.js
- src/pages/DetailPage/DetailPage.jsx
- src/pages/WriteBoard/WriteBoard.jsx
- src/services/api.js
- src/services/postApi.js
- 제목 : feat(#58): 게시글 작성 api 구현
<br/>
- 게시글 작성 시 post로 데이터 전송
<br/>
>코드 리뷰 부탁 드립니다
Closes #58
> Feat/#58 게시글 작성 api 구현

- src/Layout/Navbar/Navbar.jsx
- src/components/Card/PostCard/PostProfile.jsx
- src/components/Common/PostCollection.jsx
- src/pages/MyPage/MyProfile/MyProfile.jsx
- src/routes/Router.js
- src/services/authApi.js
- 제목 : feat(#81 ): 내가 작성한 게시글 api 구현
<br/>
- 프로필 조회한 사람이 '나'인 경우만 내가 작성한 글이 보이도록 설정
- api 구현
<br/>
Closes #81
> Feat/#81 내가 작성한 게시글 api 구현

- src/App.test.js
- src/pages/DetailPage/DetailPage.jsx
- src/pages/WriteBoard/WriteBoard.jsx
- src/services/api.js
- src/services/postApi.js
- 제목 : feat(#62 ): 글 상세페이지 api 구현
<br/>
- 글 상세 페이지 api 구현
- 코드 작성 시 실제api를 불러오면 에러 발생하기에 일단 주석 처리 해두었습니다.
<br/>
> 코드 리뷰 부탁드립니다
Closes #62
> Feat/#62 글 상세페이지 api 구현

- src/services/api/postApi.js
- 제목 : feat(#123 ): 게시글 삭제 api 수정
<br/>
- 회원 및 게시글 삭제 api 수정
<br/>
Closes #123
> feat(#123): 게시글 삭제 api 수정

- src/components/Card/PostCard/PostProfile.jsx
- src/pages/MyPage/EditProfile/EditProfile.jsx
- src/pages/MyPage/MyProfile/MyProfile.style.js
- src/services/postApi.js
- 제목 : feat(#141 ): 마이페이지 수정
<br/>
- 마이페이지 수정
<br/>
Closes #141
> feat(#141): 마이페이지 수정

- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- 제목 : feat(#143): 코드 리펙토링
<br/>
- 코드 리펙토링
> fix(#143): 코드 리펙토링

- package-lock.json
- package.json
- src/Layout/BoardLayout/BoardLayout.jsx
- src/Layout/BoardLayout/BoardLayout.style.js
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/Layout/Sidebar/Sidebar.jsx
- src/Layout/Sidebar/Sidebar.style.js
- src/components/Modal/LoginModal/LoginModal.jsx
- src/components/Modal/LoginModal/LoginModal.style.js
- src/services/api/authApi.js
- src/services/api/postApi.js
- 제목 : feat(#143 ): 게시판 or 나브바 반응형 구현
<br/>
- 게시판, 나브바 반응형으로 구현
<br/>
<br/>
Closes #143
> feat(#143): 게시판 or 나브바 반응형 구현

- .idea/.gitignore
- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/team-project-front.iml
- .idea/vcs.xml
- package-lock.json
- package.json
- src/App.js
- src/Layout/BoardLayout/BoardLayout.jsx
- src/Layout/BoardLayout/BoardLayout.style.js
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/Layout/Sidebar/Sidebar.style.js
- src/assets/styles/GlobalStyle.js
- src/components/Card/imgUploadCard/imageUpload.style.js
- src/components/Common/imgSlide.jsx
- src/components/Modal/NavBarSideModal/NavBarSideModal.jsx
- src/components/Modal/NavBarSideModal/NavBarSideModal.style.js
- src/hooks/useScreenResize.js
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/Board/BoardDetail/Board/BoardDetail.style.js
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.style.js
- src/pages/Board/BoardWrite/WriteBoard/editor.js
- src/services/api/postApi.js
- src/store/index.js
- src/store/screenResize/screenSlice.js
- 제목 : feat(#148): 글 상세페이지, 글 작성 페이지 반응형 구현
<br/>
- 글 상세페이지, 글 작성 페이지 반응형 구현
<br/>
<br/>
Closes #148
> Feat/#148 글 상세페이지, 글 작성 페이지 반응형 구현

- .idea/.gitignore
- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/team-project-front.iml
- .idea/vcs.xml
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/Layout/Sidebar/Sidebar.style.js
- src/components/Modal/NavBarSideModal/NavBarSideModal.jsx
- src/components/Modal/NavBarSideModal/NavBarSideModal.style.js
- src/services/api/postApi.js
<br/>
- 반응형 네비게이션 모달을 따로 생성하고 드롭다운 버튼을 눌렀을 경우 모달을 불러옴
- 기존 네비게이션 바에 있던 BorderButton 들도 모달안에 추가
<br/>
<br/>
모달 구현할 때 필요한 props 들을 많이 사용하였는데 이 부분 관련해서 피드백을 듣고 싶습니다.
Closes #147
> feat(#147) : 반응형 네비게이션 모달 구현

- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/components/Modal/NavBarSideModal/NavBarSideModal.jsx
<br/>
- 마이페이지 로그인 시에만 나오게 적용
- 로고 보이게 변경
- 스크롤시 드롭다운 버튼도 같이 내려가는 현상 막기
- store 활용한 반응형 적용
<br/>
<br/>
> UseSelector를 이용해서 프롭스를 줄였음에도 아직 반응형 네브 모달에 많은 프롭스가 들어가 있습니다.
- 2개 감소 (isDarkMode, isLoggedIn)
Closes #<147>
> feat(#147) : 햄버거 버튼을 이용한 모바일 네브바 구현

- src/Layout/Navbar/Navbar.style.js
- src/components/Modal/NavBarSideModal/NavBarSideModal.jsx
- src/components/Modal/NavBarSideModal/NavBarSideModal.style.js
<br/>
- 네브바 사이드 모달 스크롤 기능 구현
- 메인 페이지 에서 로고 안 보이는 버그 수정 
<br/>
- 요구 사항 이행 완료
Closes #<147>
> feat (#147) : 네브바 사이드 모달 스크롤 기능 구현

- src/components/Common/LodingSpinner.jsx
- src/pages/Board/Board.style.js
- src/pages/Board/FreeBoard/FreeBoard.jsx
- src/pages/Board/NoticeBoard/NoticeBoard.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- src/services/api/postApi.js
- 제목 : feat(#159): 무한스크롤 구현
<br/>
- 무한 스크롤 구현
<br/>
<br/>
> 파일 구조 충돌 해결.
> feat(#159): 무한스크롤 구현

- src/pages/Board/FreeBoard/FreeBoard.jsx
- src/pages/Board/FreeBoard/FreeBoard.style.js
- src/pages/Board/NoticeBoard/NoticeBoard.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.style.js
- src/pages/MainPage/MainPage.jsx
- 제목 : feat(#164): 메인 페이지 및 게시글 목록 페이지 반응형 구현
<br/>
- 메인 페이지 반응형 웹 구현
- 게시글 목록 페이지 반응형 웹 구현
<br/>
<br/>
>
> 병합 하면서 충돌할 요소가 있는지 확인하기
> Feat/#164 메인 페이지, 게시글 목록 페이지 반응형 웹 구현

- src/components/Card/PostCard/PostProfile.jsx
- src/pages/MyPage/EditProfile/EditProfile.style.js
<br/>
- 마이 페이지 반응성구현
- 편집 페이지 반응성구현
<br/>
Closes #<166>
> feat (#166) :마이페이지 반응성 구현

- src/Layout/BoardLayout/BoardLayout.jsx
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Navbar/Navbar.style.js
- src/Layout/Sidebar/Sidebar.jsx
- src/assets/styles/ErrMsg.style.js
- src/components/Modal/LoginModal/LoginModal.jsx
- src/components/Modal/LoginModal/LoginModal.style.js
- src/components/Modal/NavBarSideModal/NavBarSideModal.jsx
- src/components/Modal/NavBarSideModal/NavBarSideModal.style.js
- src/components/Modal/PasswordChange/PasswordChange.jsx
- src/components/Modal/PasswordChange/PasswordChange.style.js
- src/components/Modal/SignUpModal/UserDetailsInputForm/UserDetailsInputForm.jsx
- src/pages/Board/Board.style.js
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/Board/FreeBoard/FreeBoard.jsx
- src/pages/Board/NoticeBoard/NoticeBoard.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- src/pages/MyPage/EditProfile/EditProfile.jsx
- src/pages/MyPage/MyProfile/MyProfile.jsx
- src/routes/Router.js
- src/services/api/authApi.js
- src/services/api/postApi.js
- src/store/user/userSlice.js
- 제목 : feat(#163): api 리펙토링
<br/>
- api 리펙토링
Closes #163
> Feat/#163 api 리펙토링

- src/Layout/Sidebar/Sidebar.jsx
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/Board/BoardWrite/PostForm/postForm.jsx
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- src/services/api/authApi.js
- src/services/api/postApi.js
- 제목 : feat(#169): 유저 api, 게시글 api 구현
<br/>
- 유저 api, 게시글 api 구현
Closes #169
> feat(#169): auth: 회원가입, 로그인, 인증 연결, post: 전체 불러오기, 상세 불러오기, 카테고리 구현

- src/App.js
- src/Layout/Navbar/Navbar.jsx
- src/components/Modal/FormInputField.jsx
- src/components/Modal/LoginModal/LoginModal.jsx
- src/components/Modal/SignUpModal/UserDetailsInputForm/UserDetailsInputForm.jsx
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/services/api/authApi.js
- src/services/axiosConfig.js
- 제목 : feat(#169): axiosConfig 수정, 404 에러 수정, 로그인, 회원가입 수정
<br/>
- feat(#169): axiosConfig 수정, 404 에러 수정, 로그인, 회원가입 수정
<br/>
> feat(#169): axiosConfig 수정, 404 에러 수정, 로그인, 회원가입 수정

- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/Board/BoardWrite/PostForm/postForm.jsx
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- src/pages/Board/FreeBoard/FreeBoard.jsx
- src/pages/Board/NoticeBoard/NoticeBoard.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- src/services/api/postApi.js
- 제목 : feat(#177 ): 게시글 관련 API 연동 작업
<br/>
게시글 전체 조회 API 연동
게시글 상세 조회 API 연동
게시글 생성 API 연동
게시글 수정 API 연동
게시글 삭제 API 연동
게시글 상세 조회시 게시글 생성일자 형식 변환
<br/>
<br/>
>
> 병합 충돌 해결
> feat(#177): 게시글 관련 API 연동 작업

- src/components/Modal/NavBarSideModal/NavBarSideModal.jsx
- 제목 : feat (#175) 모달에 성공적으로 유저 정보 불러오기
<br/>
- useUserInfo 커스텀 훅 생성
- useJwt 이용해서 사용자 정보 페이로드
<br/>
기존 토큰 액세스 하는 훅만 있었는데 useJwt 훅을 이용해 유저 정보 자체를 가져오는 커스텀 훅 생성했는데 평가 해주시고
보완할 부분 있으면 말씀해주셨으면 감사하겠습니다.
Closes #<feat/#175>
> refactor (#175) : 새로운 커밋 추가

- src/components/Common/Comment/Comment.jsx
- src/components/Common/Comment/Comment.style.js
<br/>
- 183번 커밋하지 못한 작업 
<br/>
> 최신 작업입니다.
> feat (#184) : 183번 커밋 최신화한 브랜치

- src/components/Card/PostCard/PostCard.style.js
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- 제목 : feat(#185 )
<br/>
- 기타 오류 처리
<br/>
<br/>
>
> feat(#194) : 기타 오류 처리

- src/Layout/BoardLayout/BoardLayout.style.js
- src/components/Card/PostCard/NoticePostCard/NoticePostCard.style.js
- src/pages/Board/Board.style.js
- src/pages/Board/FreeBoard/FreeBoard.jsx
- src/pages/Board/NoticeBoard/NoticeBoard.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- 제목 : feat(#197)
<br/>
- 무한 스크롤 개선
- 기타 UI 오류 수정
<br/>
<br/>
>
> feat(#201) : 무한 스크롤 개선 및 UI 오류 수정

- src/assets/styles/ErrMsg.style.js
- src/components/Card/MyPostsCard/MyPosts/MyPosts.jsx
- src/components/Modal/FormInputField.jsx
- src/components/Modal/LoginModal/LoginModal.jsx
- src/components/Modal/SignUpModal/SignUpModal.jsx
- src/components/Modal/SignUpModal/UserDetailsInputForm/UserDetailsInputForm.jsx
- src/pages/MyPage/EditProfile/EditProfile.jsx
- src/pages/MyPage/MyProfile/MyProfile.jsx
- src/services/api/authApi.js
- 제목 : feat(#196): 프론트 에러 사항 해결
<br/>
- GlobalStyle 적용
- 회원가입 에러 표시 해결
Closes #196
> Feat/#196 프론트 에러 사항 해결

- src/Layout/Navbar/Navbar.jsx
- src/assets/styles/ErrMsg.style.js
- src/components/Card/MyPostsCard/MyPosts/MyPosts.jsx
- src/components/Card/MyPostsCard/PostsByCategory/PostsByCategory.jsx
- src/components/Modal/LoginModal/LoginModal.jsx
- src/components/Modal/SignUpModal/SignUpModal.jsx
- src/components/Modal/SignUpModal/SignUpModal.style.js
- src/components/Modal/SignUpModal/UserDetailsInputForm/UserDetailsInputForm.jsx
- src/pages/MyPage/MyProfile/MyProfile.jsx
- src/services/api/authApi.js
- 제목 : feat(#196): 내가 작성한 글 api 에러 해결, 에러 메세지 css 수정
<br/>
-  내가 작성한 글 api 에러 해결
- 에러 메세지 css 수정
<br/>
Closes #196
> refactor(#196): 내가 작성한 글 api 에러 해결, 에러 메세지 css 수정

- src/services/api/authApi.js
- 제목 : feat(#205): 로그인, 회원가입 api url 수정
<br/>
- 로그인, 회원가입 api url 수정
Closes #205
> refactor(#205): 로그인, 회원가입 api url 수정

- src/pages/MyPage/EditProfile/EditProfile.jsx
- src/services/api/authApi.js
- src/services/api/imageApi.js
- src/services/api/postApi.js
- 제목 : feat(#207): presignedurl api 구현 및 api url 수정
<br/>
-  presignedurl api 구현
- api url 수정
<br/>
Closes #207
> feat(#207): presignedurl api 구현 및 api url 수정

- .idea/inspectionProfiles/Project_Default.xml
- src/Layout/Navbar/Navbar.jsx
- src/Layout/Sidebar/Sidebar.jsx
- src/components/Card/PostCard/CommunityPostCard/CommunityPostCard.jsx
- src/components/Card/PostCard/CommunityPostCard/CommunityPostCard.style.js
- src/components/Card/PostCard/ProjectPostCard/ProjectPostCard.jsx
- src/components/Card/imgUploadCard/imageUpload.style.js
- src/components/Common/Interactions.jsx
- src/components/Common/PopularPost/PopularPostSlider.js
- src/components/Common/PopularPost/PopularPostSlider.style.js
- src/components/Modal/ConfirmDeleteModal/ConfirmDeleteModal.jsx
- src/components/Modal/ConfirmDeleteModal/ConfirmDeleteModal.style.js
- src/pages/Board/Board.style.js
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/Board/BoardDetail/Board/BoardDetail.style.js
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.style.js
- src/pages/Board/FreeBoard/FreeBoard.jsx
- src/pages/Board/NoticeBoard/NoticeBoard.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- src/pages/MainPage/MainPage.jsx
- src/services/api/postApi.js
- src/store/category/categorySlice.js
- src/store/index.js
- src/store/menu/menuSlice.js
- 제목 : feat(#217 ): 
<br/>
진행한 작업 내역
- 게시글 전체 조회, 상세 조회 요청 형식 변경
- 게시글 작성, 수정, 삭제 요청 형식 변경
- 인기게시글 임시 처리 형식 변경
- 전체 게시글 정렬 기능 적용
- 게시글 검색 임시 처리
- isMe 확인 안되는 문제 해결
- 게시글 내용 좌측 하단 해시태그 없을시 기본값 # 지정
- 프로젝트 게시판, 질문 게시판, 공지사항 게시판에도 형식 변경 적용.
- 게시글 상세 조회 페이지 디자인 수정
- 게시글 작성 페이지 디자인 수정
- 게시글 하단 그림자 짤리는거 해결
- 반응형 구현
<br/>
<br/>
>
> Feat/#217 변경된 게시글 api 형식 적용 및 게시글 페이지 디자인 수정

- src/components/Card/PostCard/ProjectPostCard/ProjectPostCard.jsx
- src/components/Card/imgUploadCard/imageUploadCard.jsx
- src/components/Common/PopularPost/PopularPostSlider.js
- src/components/Common/PopularPost/PopularPostSlider.style.js
- src/components/Common/Search/Search.jsx
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/Board/BoardWrite/PostForm/postForm.jsx
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- src/pages/Board/FreeBoard/FreeBoard.jsx
- src/pages/Board/NoticeBoard/NoticeBoard.jsx
- src/pages/Board/ProjectBoard/ProjectBoard.jsx
- src/pages/Board/QuestionBoard/QuestionBoard.jsx
- src/services/api/imageApi.js
- src/services/api/postApi.js
- 제목 : feat(issue 번호): 기능명
ex) feat(#17): pull request template 작성
(확인 후 지워주세요)
<br/>
- 프로젝트 게시글 api 적용 (DELETE 까지 적용 됬으나, 백 api 문제로 삭제 처리가 안되는 문제 발생.)
- 인기 게시글 조회 오류 수정 (인기 게시글 조회시 HOT 으로 불러온걸 불필요하게 댓글수로 정렬하는 부분이 남아 있어서 제거함.)
- 인기 게시글 디자인 오류 수정 (슬라이더 하단의 중첩 dot를 제거함.)
<br/>
<br/>
>
> feat(#222): 프로젝트 게시글 api 일부 적용 및 임시 인기 게시글 조회 오류 수정, 인기 게시글 디자인 오류 수정

- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- src/services/api/postApi.js
- 제목 : feat(#232 ):
<br/>
- 썸네일 등록 오류 해결
- isMe 처리 부분 수정
<br/>
<br/>
>
> feat(#232): 썸네일 등록 오류 해결 및 isMe 처리 부분 수정

- babel.config,js
- package-lock.json
- package.json
- src/Layout/ProfileLayout/DeskTop/DesktopProfile.jsx
- src/Layout/ProfileLayout/Mobail/MobailProfile.jsx
- src/Layout/ProfileLayout/ProfileLayout.jsx
- src/Layout/Sidebar/Sidebar.jsx
- src/assets/styles/Font.style.js
- src/components/Card/MyPostsCard/MyPosts/MyPosts.style.js
- src/components/Card/PostCard/CommunityPostCard/CommunityPostCard.jsx
- src/components/Card/PostCard/PostCard.style.js
- src/components/Card/PostCard/ProjectPostCard/ProjectPostCard.jsx
- src/components/Common/Interactions.jsx
- src/components/Common/PopularPost/PopularPostSlider.jsx
- src/components/Common/PopularPost/PopularPostSlider.style.js
- src/components/Modal/SignUpModal/SignUpModal.style.js
- src/components/Modal/SignUpModal/UserDetailsInputForm/UserDetailsInputForm.jsx
- src/components/Modal/SignUpModal/UserDetailsInputForm/UserDetailsInputForm.style.js
- src/hooks/useJwt.js
- src/pages/Board/BoardDetail/Board/BoardDetail.jsx
- src/pages/MyPage/EditProfile/EditProfile.jsx
- src/pages/MyPage/EditProfile/EditProfile.style.js
- src/pages/MyPage/MyProfile/DeskTop/MyProfile.jsx
- src/pages/MyPage/MyProfile/Mobail/MyProfile.jsx
- src/pages/MyPage/MyProfile/Mobail/MyProfile.style.js
- src/routes/Router.js
- src/services/api/authApi.js
- src/services/api/postApi.js
- 제목 : feat(#231): 디자인 에러 및 기능 에러 해결
<br/>
Closes #231
> Feat/#231 디자인 에러 및 기능 에러 해결

- .gitignore
- babel.config,js
- babel.config.js
- package-lock.json
- package.json
- src/components/Card/PostCard/CommunityPostCard/CommunityPostCard.jsx
- src/components/Card/PostCard/CommunityPostCard/CommunityPostCard.style.js
- 제목 : feat(#231): 콘솔 제거
<br/>
- 콘솔 제거
> Feat/#231 콘솔 제거

- src/components/Card/PostCard/ProjectPostCard/ProjectPostCard.jsx
- src/pages/Board/BoardWrite/WriteBoard/BoardWrite.jsx
- 제목 : feat(issue 번호): 기능명
ex) feat(#17): pull request template 작성
(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
>
> feat(#test1): 글작성 기본 썸네일 에러 해결
